//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by Gen_m3a.rc
//
#define IDD_CONFIG_v290                 101
#define IDD_CONFIG_v500                 102
#define IDD_CONFIGABOUT_v500            103
#define IDD_CONFIGHISTORY_v500          104
#define IDD_CONFIGPATH                  105
#define IDD_CONFIGOPTION_v500           106
#define IDD_CONFIGNAMING                107
#define IDD_CONFIGABOUT_v290            108
#define IDD_CONFIGHISTORY_v290          109
#define IDD_CONFIGOPTION_v290           111
#define IDD_ALBUMLIST                   113
#define IDD_CONFIGLANGUAGE_v500         114
#define IDD_ALBUMINFO                   115
#define IDD_CONFIGPROFILE_v500          116
#define IDD_CONFIGLANGUAGE_v290         117
#define IDD_CONFIGPROFILE_v290          118
#define IDD_PREFERENCE                  119
#define IDR_ACCELERATOR_AL              120
#define IDB_COVER                       121
#define IDB_ICON_AL_H                   124
#define IDB_ICON_AL                     125
#define IDB_COVER_MASK                  126
#define IDD_PROFILENAME                 129
#define IDD_JUMPTOALBUM                 185
#define IDD_CONFIGCOVER                 186
#define IDD_CONFIGABOUT_ML              187
#define IDD_TABBED_UI                   188
#define IDC_TAB                         1000
#define IDC_EDIT                        1001
#define IDC_PATHLIST                    1002
#define IDC_RENAME                      1002
#define IDC_ADD                         1003
#define IDC_REMOVE                      1004
#define IDC_REMOVEALL                   1005
#define IDC_FILETYPEEDIT                1006
#define IDC_SCAN_AT_STARTUP             1007
#define IDC_SCANSUBDIR                  1008
#define IDC_ADD_CDROM                   1009
#define IDC_IGNORE_M3U                  1010
#define IDC_IGNOREPL                    1011
#define IDC_IGNORE_M3U_ROOT             1011
#define IDC_AUTOADVANCE                 1012
#define IDC_STYLE                       1013
#define IDC_LANGUAGE                    1014
#define IDC_RESUME                      1015
#define IDC_SORTFILENAME                1016
#define IDC_LOOPNEXTPREV                1017
#define IDC_KEEPSONGPLAYING             1018
#define IDC_ALBUMBTN                    1019
#define IDC_PLAYBTN                     1019
#define IDC_ENQUEUE                     1020
#define IDC_ENQUEUEBTN                  1020
#define IDC_SHOWCOVER                   1021
#define IDC_FIXTITLES                   1022
#define IDC_MULTIDISCFIX                1023
#define IDC_USEID3                      1024
#define IDC_MULTIDISCNAMES              1025
#define IDC_ALBUMLIST                   1026
#define IDC_SCROLLBAR1                  1027
#define IDC_VERSION_STATIC              1028
#define IDC_PATH                        1029
#define IDC_TRANSLATED_BY               1030
#define IDC_FILECOUNT                   1031
#define IDC_AL_LANG                     1032
#define IDC_LENGTH                      1033
#define IDC_PE_LANG                     1034
#define IDC_ARTIST                      1035
#define IDC_PLAYLISTEDITOR              1036
#define IDC_ALBUM                       1037
#define IDC_YEAR                        1038
#define IDC_LISTNAME                    1039
#define IDC_PROFILELIST                 1040
#define IDC_GENRE                       1040
#define IDC_NEW                         1041
#define IDC_DELETE                      1042
#define IDC_PROFILELIST2                1043
#define IDC_IGNORETHE                   1044
#define IDC_CHECK_UPDATE                1045
#define IDC_RANDOM                      1046
#define IDC_USEBUILTIN                  1047
#define IDC_USEWAEINFO                  1048
#define IDC_TOTALALBUMTIME              1049
#define IDC_LIGHTNING_BOLT              1051
#define IDC_CURRENT_ALBUM               1052
#define IDC_INTEGRATEML                 1054
#define IDC_COVER_WIDTH                 1055
#define IDC_COVER_HEIGHT                1056
#define IDC_SPIN1                       1057
#define IDC_COVER_WIDTH_SPIN            1057
#define IDC_SPIN2                       1058
#define IDC_COVER_HEIGHT_SPIN           1058
#define IDC_BORDER_WIDTH                1059
#define IDC_SPIN3                       1060
#define IDC_BORDER_WIDTH_SPIN           1060
#define IDC_CACHE_THUMBNAILS            1061
#define IDC_COLOR                       1062
#define IDC_COLORCHOOSER                1063
#define IDC_DEFAULT_COVER               1064
#define IDC_BROWSE                      1065
#define IDC_TEXT_COLOR                  1066
#define IDC_TEXTCOLORCHOOSER            1067
#define IDC_SHADOW                      1068
#define IDC_PLAYALL_WARNING             1069
#define IDC_ALTERNATE_FOLDER            1069
#define IDC_PLAYALL_LIMIT               1070
#define IDC_BROWSE2                     1070
#define IDC_PLAYALL_GT                  1071
#define IDC_PLAYALL_ALBUM               1072
#define IDC_M3U_ONLY                    1073
#define IDC_MSN                         1074
#define IDC_USE_ALT_FOLDER              1075
#define IDC_OVERRIDE_DEF_COVER          1076
#define IDC_INSIDE_MP3                  1077
#define IDC_TEXT_COLOR_STATIC           1078
#define IDC_PLAY                        1079
#define IDC_DRAWTITLE                   1081
#define IDC_SEARCH_ORDER                1082
#define IDC_CACHE_COVERS                1083
#define IDC_MULTIDISC                   1088
#define IDC_PREVALBUMBTN                1089
#define IDC_NEXTALBUMBTN                1090
#define IDC_NEXTALBUM                   1090
#define IDC_PROFILE_EDIT                1090
#define IDC_SEARCH_ALBUM_DIR            1091
#define IDC_BORDER_COLOR                1092
#define IDC_STATIC_PE                   1093
#define IDC_SEARCH_STATIC               1094
#define IDC_RESULTLIST                  1122
#define IDC_SEARCHTEXT                  1206
#define IDC_NEW_PROFILE                 1207
#define IDC_PREFERENCE                  1208
#define IDC_RENAME_PROFILE              1209
#define IDC_DELETE_PROFILE              1210
#define IDC_TOGGLE_VIEW                 40001
#define IDC_KEYPAD0                     40002
#define IDC_KEYPAD1                     40003
#define IDC_KEYPAD2                     40004
#define IDC_KEYPAD3                     40005
#define IDC_KEYPAD4                     40006
#define IDC_KEYPAD5                     40007
#define IDC_KEYPAD6                     40008
#define IDC_KEYPAD7                     40009
#define IDC_KEYPAD8                     40010
#define IDC_KEYPAD9                     40011
#define IDC_PLAY_ALBUM                  60061
#define IDC_ENQUEUE_ALBUM               60062
#define IDC_SHOW_ALBUM_COVER            60063
#define IDC_WRITE_PLAYLIST              60064
#define IDC_REFRESH_ALBUM               60065
#define IDC_SHOW_ALBUM_INFO             60066
#define IDC_PLAY_ALL_ALBUMS             60067
#define IDC_EXPORT_ALBUM_LIST           60068
#define IDC_RELOAD_ALBUM                60069
#define IDC_QUICK_SCAN_ALBUM            60070
#define IDC_PLAY_RANDOM_ALBUM           60071
#define IDC_SHOW_PROPERTIES             60072
#define IDC_SORT_PATH                   60073
#define IDC_SORT_NAME                   60074
#define IDC_SORT_ARTIST                 60075
#define IDC_SORT_YEAR                   60076
#define IDC_SORT_NUMOFSONGS             60077
#define IDC_SORT_TOTALTIME              60078
#define IDC_SORT_SHUFFLE                60079
#define IDC_HEADER_TITLE                60080
#define IDC_HEADER_YEAR                 60081
#define IDC_HEADER_TIME                 60082
#define IDC_HEADER_NUMOFSONGS           60083
#define IDC_TIMEFORMAT1                 60084
#define IDC_TIMEFORMAT2                 60085
#define IDC_EXPLORE                     60086
#define IDC_AUTOSIZECOLUMN              60087
#define IDC_PLAY_ALBUM_BY_ARTIST        60088
#define IDC_SHOWINDEXNUM                60089
#define IDC_AUTOHIDEHEADER              60090
#define IDC_PLAY_MENU                   60091
#define IDC_JUMP_TO_ALBUM               60092
#define IDC_HEADER_PATH                 60093
#define IDC_HEADER_ARTIST               60094
#define IDC_HEADER_ALBUM                60095
#define IDC_SORT_ALBUM                  60096
#define IDC_COVER_VIEW                  60097
#define IDC_LIST_VIEW                   60098
#define IDC_SHOW_STATUS                 60099
#define IDC_NEXT_ALBUM                  60100
#define IDC_PREV_ALBUM                  60101
#define IDC_ENQUEUE_N_PLAY              60102
#define IDC_ENQUEUE_AFTER_CUR           60103
#define IDC_SORT_ARTIST_YEAR            60104
#define IPC_ADD_MENU                    60105
#define IDC_HEADER_MULTIDISC            60106
#define IDC_HEADER_GENRE                60107
#define IDC_SORT_GENRE                  60108
#define IPC_ADD_MENU_LAST               60205
#define IDC_SHOW_HEADER                 60206
#define IDC_PLAY_RANDOM_ALBUM_BY_ARTIST 60207
#define IDC_SHOWFULLPATH                60208
#define IDC_SHOW_LABEL                  60209
#define IDC_SENDTO_MENU_START			60210
#define IDC_SENDTO_MENU_END				60310
#define IDC_MENU_ALBUMLIST              61234
#define IDC_ENQUEUE_RANDOM_ALBUM        61235
#define IDC_ENQUEUE_ALL_ALBUMS          61236
#define IDC_ENQUEUE_ALBUM_BY_ARTIST     61237
#define IDC_ENQUEUE_RANDOM_ALBUM_BY_ARTIST 61238

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        130
#define _APS_NEXT_COMMAND_VALUE         40006
#define _APS_NEXT_CONTROL_VALUE         1095
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
